# Generated by Django 2.0.2 on 2018-04-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema1',
            fields=[
                ('cinema_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('cinema_name', models.CharField(max_length=50)),
                ('cinema_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_details', models.TextField()),
                ('movie_pic', models.ImageField(upload_to='')),
                ('movie_img', models.CharField(max_length=100)),
                ('movie_vid', models.CharField(max_length=100)),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema1')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('offer_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Puser',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('bdate', models.DateTimeField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Puser_offer',
            fields=[
                ('user_no', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('ur_name', models.CharField(max_length=30)),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('random_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('random_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('time', models.DateTimeField()),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema1')),
                ('movie_id', models.ForeignKey(on_delete='true', to='login.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('show_id', models.ForeignKey(on_delete='true', to='login.Show')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Puser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete='true', to='login.Offers')),
                ('ticket_id', models.ForeignKey(on_delete='true', to='login.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='c_city',
            name='cinema_id',
            field=models.ForeignKey(on_delete='true', to='login.Cinema1'),
        ),
        migrations.AddField(
            model_name='c_city',
            name='city_id',
            field=models.ForeignKey(on_delete='true', to='login.City'),
        ),
    ]
