# Generated by Django 2.0.2 on 2018-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=30)),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema1')),
                ('city_id', models.ForeignKey(on_delete='true', to='login.City')),
                ('movie_id', models.ForeignKey(on_delete='true', to='login.Movie')),
                ('show_id', models.ForeignKey(on_delete='true', to='login.Show')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Puser')),
            ],
        ),
    ]
