# Generated by Django 2.0.2 on 2018-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_ticket_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_n',
            name='cinema_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_n',
            name='city_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_n',
            name='movie_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_n',
            name='show_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_n',
            name='user_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_n',
            name='user_name_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
