# Generated by Django 2.0.2 on 2018-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180411_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=30)),
                ('admin_cinema_work', models.CharField(max_length=30)),
                ('admin_city_work', models.CharField(max_length=30)),
                ('admin_email_id', models.CharField(max_length=30)),
                ('admin_mobile_no', models.CharField(max_length=30)),
            ],
        ),
    ]
